micronaut:
    application:
        name: sample
    server:
        port: 8080
    datasources:
        default:
            url: jdbc:mysql://localhost:3306/gps
            username: shan
            password: Shan2018
            driverClassName: com.mysql.jdbc.Driver

