micronaut:
    application:
        name: sample
    server:
        port: 8080
datasources:
    default:
        name: 'mydb'
        url: jdbc:mysql://localhost:3306/gps
        username: shan
        password: shan2018
        driverClassName: com.mysql.jdbc.Driver
jpa:
    default:
        packages-to-scan:
             - 'sample.dao'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true